# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcb821e10d17cd3665bec585fbcf0da256c53f09fb845c990479fc5612c70f1f514d929894da44454c286d9b8ae07c0b5f731cbcfff4509dad953e84958dda57

test:
  secret_key_base: 8104c4a38b9bcc33fc8c9ef030fce61f72d8cf3658c9d18e74dbfa7fdc447665aaefbe1a14d06e4b4e2b27ba75490cc587761ff266a1070a8f7e4e085e9d80a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
